name: isar
description: Fast Cross Platform Database for Flutter Apps. Supports indexes, FTS, queries etc.
version: 2.6.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.0
  js: ^0.6.7
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.6
  ffigen: ^7.0.0
  lints: ^2.0.1
